- name: variables from files
  hosts: web
  vars_files:
  - vars.yml
  tasks: 
  - name: print the information
    ansible.builtin.debug:
      msg: "Hi, I am learing {{ COURSE }}, Duration is: {{ DURATION }}, Trainer: {{ TRAINER }}"


