- name: variables to print
  hosts: web
  vars: #play level, all tasks in this play have access to this 
    COURSE: "Devops with AWS from play level"
    DURATION: "120Hrs"
    TRAINER: "Sivakumar REddy"
  vars_files:
  - vars.yml 
  vars_prompt:
  - name: COURSE
    prompt: Please enter the course name
    private: false  
  tasks:
  - name: print the information
    vars: #play level, all tasks in this play have access to this 
      #COURSE: "Devops with AWS from task level"
      DURATION: "120Hrs"
      TRAINER: "Sivakumar REddy"
    ansible.builtin.debug:
      msg: "Hi, I am learning {{COURSE}}"





#1. COMMAND LINE/ ARGS
#2. TASK
#3. FILES
#4. PROMPT
#5. PLAY
#6. INVENTORY


  