---
- name: check a number is less than 10 mor not
  hosts: local
  connection: local
  vars_prompt:
  - name: my_number
    prompt: Please enter the number
    private: false # not confidential
  tasks: 
  - name: print this if less than 10
    ansible.builtin.debug:
      msg: "Give number {{ my_number }} is less than 10"
    when: my_number | int < 10 

  - name: print this if greater than or equal to 10
    ansible.builtin.debug:
      msg: "Given number {{ my_number }} is greater than 10"
    when: my_number | int >= 10     