- name: create ec2 and R53 
  hosts: local
  connection: local
  vars: 
    subnet_id: subnet-029443e56df21408a
    sg_id: sg-005d29d3e5600a71e
    ami_id: ami-09c813fb71547fc4f
    instances: 
    - mysql
    - backend
    - frontend
    zone: devops1289.online
  tasks:
  - name: create ec2 instance
    amazon.aws.ec2_instance:
      name:
      vpc_subnet_id: "{{ subnet_id }}"
      instance_type: "t3.micro"
      security_group: "{{ sg_id }}"
      image_id: "{{ ami_id }}" 
    loop: "{{ instances }}"
    register: ec2_instances

  - name: print the output
    ansible.builtin.debug:
      msg: "{{ ec2_instances }}"

  - name: create R53 records
    amazon.aws.route53:
       state: present
       zone: "{{ zone }}"
       record: "{{ item.item }}.{{ zone }}"
       type: A
       ttl: 1
       value: "{{ item.instance[0].private_ip_address }}"
       wait: true
       overwrite: True
    loop: "{{ ec2_instance.results }}"   

